[default.extend-words]
ser = "ser"
Referer = "Referer"
Encryp = "Encryp"
OT = "OT"
Wheres = "Wheres"
ws = "ws"
guid = "guid"
yoy = "yoy"
Ein = "Ein"
Datas = "Datas"
[files]
extend-exclude = ["mapFiles/**", "docs"]
